loadFramePacks([
	{name:'Misc. Custom Frames', value:'MiscCustom'},
	{name:'Deck Covers', value:'CustomDeckCover'},
	{name:'Simple Inventions', value:'SimpleInventions'},
	{name:'Tapped (Horizontal M15)', value:'Tapped'},
	{name:'Textless Duals', value:'CustomDualLands'},
	{name:'Textless Seventh', value:'SeventhTextless'},
	{name:'Seventh Edition Planeswalkers', value:'PlaneswalkerSeventh'},
	{name:'Seventh Edition Sagas', value:'OldSaga'},
	{name:'Seventh Edition Snow Lands', value:'SeventhSnowLands'},
	{name:'Floating Old Border', value:'OldFloating'},
	{name:'Floating Old Border (Short)', value:'OldFloatingShort'},

	{name:'Modern M15 Eighth Edition Style', value:'disabled'},
	{name:'Regular', value:'M15Eighth'},
	{name:'Nyx', value:'M15EighthNyx'},
	{name:'Snow', value:'M15EighthSnow'},
	{name:'Universes Beyond', value:'M15EighthUB'},

	{name:'Modern M15 Eighth Edition Transform', value:'disabled'},
	{name:'Regular (Front)', value:'M15EighthTransformFront'},
	{name:'Regular (Back)', value:'M15EighthTransformBack'},
	{name:'Nyx (Front)', value:'M15EighthTransformNyxFront'},
	{name:'Nyx (Back)', value:'M15EighthTransformNyxBack'},
	{name:'Snow (Front)', value:'M15EighthTransformSnowFront'},
	{name:'Snow (Back)', value:'M15EighthTransformSnowBack'},
	{name:'Universes Beyond (Front)', value:'M15EighthTransformUBFront'},
	{name:'Universes Beyond (Back)', value:'M15EighthTransformUBBack'},

	{name:'Modern M15 Eighth Edition Tokens', value:'disabled'},
	{name:'Regular', value:'M15EighthToken'},
	{name:'Nyx', value:'M15EighthNyxToken'},
	{name:'Snow', value:'M15EighthSnowToken'},
	{name:'Universes Beyond', value:'M15EighthUBToken'},

	{name:'Modern M15 Eighth Edition Tokens (Textless)', value:'disabled'},
	{name:'Regular (Textless)', value:'M15EighthTokenTextless'},
	{name:'Nyx (Textless)', value:'M15EighthNyxTokenTextless'},
	{name:'Snow (Textless)', value:'M15EighthSnowTokenTextless'},
	{name:'Universes Beyond (Textless)', value:'M15EighthUBTokenTextless'},

	{name:'Classicshifted Series', value:'disabled'},
	{name:'Classicshifted', value:'Classicshifted'},
	{name:'Classicshifted Lands', value:'ClassicshiftedLands'},
	{name:'Classicshifted Planeswalkers', value:'ClassicshiftedPlaneswalker'},
	{name:'Classicshifted Planeswalker Transform Addons', value:'ClassicshiftedPlaneswalkerTransform'},
	{name:'Classicshifted Sagas', value:'ClassicshiftedSaga'},
	{name:'Classicshifted MDFC Addons', value:'ClassicshiftedDFC'},
	{name:'Classicshifted Transform Addons', value:'ClassicshiftedTransform'},
	{name:'Color Identity Pips', value:'ClassicshiftedCIPips'},

	{name:'Showcase Frame Varients', value:'disabled'},
	{name:'Short Neon (NEO)', value:'NEONeonShort'},
	{name:'Colored Golden Age (SNC)', value:'SNCGildedColored'},
	{name:'Textless Golden Age (SNC)', value:'SNCGildedTextless'},
	{name:'Textless Equinox (MID)', value:'EquinoxTextless'},
	{name:'Horizontal Japanese Mystical Archive (STA)', value:'MysticalArchiveJPHorizontal'},
	{name:'Extended Art Invocations', value:'AKHInvocationExtended'},
	{name:'Textless Inventions', value:'TextlessInvention'},

	{name:'Custom Addons', value:'disabled'},
	{name:'Brawl Legend Crowns', value:'Brawl'},

	{name:'Custom Community Frames', value:'disabled'},
	{name:'Cartoony - Sheepwave', value:'Cartoony'},
	{name:'Neon - Elry', value:'CustomNeon'},
	{name:'Ixalan - @feuer_ameise', value:'FeuerAmeiseIxalan'},
	{name:'Kaldheim, Fullart - @feuer_ameise', value:'FeuerAmeiseKaldheim'},
	{name:'Celid\'s Asap', value:'CustomCelidAsap'},
	{name:'Magrao\'s Kaldheim', value:'CustomMagraoKaldheim'},
	{name:'Pokemon', value:'Pokemon'},
	{name:'Circuit', value:'Circuit'}
])